### ISSUE TITLE
Chokolatey sets $url parameter

### ISSUE THREAD

**Issue by MortenChristiansen** [JetBrains/meta-runner-power-pack#43]
When building a project and Chokolatey is not installed on the build agent, the Chokolatey install script apparently defines a url parameter containing the value `https://chocolatey.org/api/v2/package/chocolatey/` which gets passed along to `gitversion.exe`. Using a local git repository (no url is specified), the following command was executed by the metarunner: `C:\ProgramData\Chocolatey\bin\gitversion.exe "C:\TeamCity\buildAgent\work\4d3ca3d2ab478a4a" /url 'https://chocolatey.org/api/v2/package/chocolatey/' /output 'buildserver' /UpdateAssemblyInfo true`. Running the build again works as expected, since the install script is not executed.

**Comment by gep13** [comment]
@MortenChristiansen just to confirm, are you referring to the GitVersion Meta Runner, which is included here:

https://github.com/JetBrains/meta-runner-power-pack/tree/master/gitversion

If so, I am not clear on exactly what you are referring to.

When running the GitVersion Meta Runner, it will first check to see whether both Chocolatey and GitVersion are installed.  If GitVersion is not installed, it will attempt to use Chocolatey to do the installation of GitVersion, and if Chocolatey is not installed, it will first install Chocolatey, and then GitVersion.  The next time the Meta Runner runs, it shouldn't need to do either of those things, instead, it will just execute GitVersion.

The $url that you define within the GitVersion Meta Runner should have no impact on Chocolatey.  The Url required to install Chocolatey is fixed.  The $url parameter for GitVersion is optional, and only required if you have not already "checked out" the source code onto the build agent.

I really can't see how you ended up with this:

`C:\ProgramData\Chocolatey\bin\gitversion.exe "C:\TeamCity\buildAgent\work\4d3ca3d2ab478a4a" /url 'https://chocolatey.org/api/v2/package/chocolatey/' /output 'buildserver' /UpdateAssemblyInfo true. `

Unless you specified that URL within the MetaRunner configuration.

@robdmoore any thoughts?

**Comment by robdmoore** [comment]
Hmm, interesting!

So we run `iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))`.

That script has `$url = "https://chocolatey.org/api/v2/package/chocolatey/"` at the top. Hence the issue.

We could run the `iex` from a function? That should scope any variables to that function right?

**Comment by gep13** [comment]
Doh! Good catch! :+1: 

Or, change the variable names to be more specific to GitVersion, i.e. GitVersionUrl.  I think your approach would have less impact though.

**Comment by MortenChristiansen** [comment]
Doh, in my haste I forgot that the runner was a part of the larger power pack, but it appears you have figured it out regardless :)
