### ISSUE TITLE
After updating TC to 9.1.5 nuget.exe default path has been changed [xUnit.net-dotCover]

### ISSUE THREAD

**Issue by AdelRefaat** [JetBrains/meta-runner-power-pack#67]
So, the param $nugetExe value should be 
`[string] $nugetExe = "%teamcity.tool.NuGet.CommandLine.DEFAULT%\tools\nuget.exe"`
instead of
`[string] $nugetExe = "%teamcity.tool.NuGet.CommandLine.DEFAULT.nupkg%\tools\nuget.exe"`

**Comment by gitfool** [comment]
My build agents became **incompatible** after installing xUnit.net-dotCover and adding a build step.

I can confirm that stopping the TeamCity Server and manually editing the xml file as above in "_TeamCityDataDir_\config\projects\_Root\pluginData\metaRunners\MRPP_xunit_dotcover.xml" fixed the problem and the build agents were compatible once again.

**Comment by petemounce** [comment]
That worked for me, too.

**Comment by gitfool** [comment]
I haven't tested it yet, but [MRPP_xunit_dotcover.xml#L7](https://github.com/JetBrains/meta-runner-power-pack/blob/5451df8ee3d330356ed8e52343bff66c8ff97f72/xUnit.net-dotCover/MRPP_xunit_dotcover.xml#L7) still has the `.nupkg` suffix... !?

**Comment by wwwlicious** [comment]
It was in the following commit
https://github.com/JetBrains/meta-runner-power-pack/blob/master/xUnit.net-dotCover/MRPP_xunit_dotcover.xml#L7
