### ISSUE TITLE
GitVersion MetaRunner can't find chocolatey properly

### ISSUE THREAD

**Issue by bradphelan** [JetBrains/meta-runner-power-pack#98]
When building my project I get

> PowerShell Executable: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
> [08:50:26]	Working directory: C:\Users\teamcity\teamcityconf\BuildAgent\trick\work\a340315af7a6407e
> [08:50:28]	Chocolatey already installed
> [08:50:28]	GitVersion not installed; installing GitVersion
> [08:50:28]	##teamcity[buildStatus text='The term __'C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd'__ is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.' status='FAILURE']
> 

![image](https://cloud.githubusercontent.com/assets/17650/25736179/9eaaa414-3170-11e7-9ec1-1a48e7e64fe2.png)

however with the latest version of chocolatey this directory does not exist

![image](https://cloud.githubusercontent.com/assets/17650/25736200/b81eedba-3170-11e7-90b9-830cff4eb4bc.png)

**Comment by gep13** [comment]
@bradphelan can you please check that you are running the most recent meta runner from this repository?  From the error message, it looks like you are running a much older version, that is trying to run the `chocolatey.cmd` files.  Neither of the current GitVersion Meta Runner's in this repo are using that file anymore, and instead are invoking the `choco.exe` directly.

**Comment by bradphelan** [comment]
Yeah that was the problem.  I figured it out myself just two minutes ago.

**Comment by gep13** [comment]
Woot! Glad to hear that you got it sorted 😄

**Comment by bradphelan** [comment]
It would be nice if teamcity had a package management system for meta-runners or at minimum a link to a git repository / gist with the ability to auto upgrade. There is nothing after the meta runner is installed to say which version it is or if there is a new version available.

**Comment by gep13** [comment]
@bradphelan yes, I agree, that would be very useful.
